SIL.AARTO.Web/Controllers/QuoteManagement/QuoteEnquiryController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using SIL.AARTO.BLL.Culture;
using SIL.AARTO.BLL.NoticeProcess;
using SIL.AARTO.BLL.Utility;
using SIL.AARTO.BLL.Utility.Cache;
using SIL.AARTO.DAL.Entities;
using SIL.AARTO.DAL.Services;
using SIL.AARTO.Web.Helpers.Paginator;
using SIL.AARTO.Web.Resource.QuoteManagement;
using SIL.AARTO.Web.ViewModels.QuoteManagement;
using Stalberg.TMS;
using Stalberg.TMS.Data;

namespace SIL.AARTO.Web.Controllers.QuoteManagement
{
    [Authorize]
    public partial class QuoteManagementController : Controller
    {
        #region Variable

        string LastUser
        {
            get { return Session["UserLoginInfo"] != null ? (this.Session["UserLoginInfo"] as UserLoginInfo).UserName : null; }
        }

        public int AutIntNo
        {
            get { return Session["autIntNo"] != null ? Convert.ToInt32(Session["autIntNo"]) : Session["UserLoginInfo"] != null ? ((UserLoginInfo)Session["UserLoginInfo"]).AuthIntNo : 0; }
        }

        public static string connectionString = ConfigurationManager.ConnectionStrings["AARTOConnectionString"].ConnectionString;
        readonly string cultureName = Thread.CurrentThread.CurrentCulture.Name;

        #endregion

        public ActionResult QuoteEnquiryList(int page = 0, string QuoteReferenceNumber = "", string UserName = "", string PaymentReceiptNumber = "", string ChargeCode = "", string BeginDate = "", string EndDate = "")
        {
            UserLoginInfo userInfo = Session["UserLoginInfo"] as UserLoginInfo;
            if (userInfo == null)
            {
                return RedirectToAction("login", "account");
            }

            int autIntNo = Convert.ToInt32(Session["autIntNo"]);

            QuoteEnquiryManagementModel model = InitialQuoteEnqiuryModel(page, QuoteReferenceNumber, UserName, PaymentReceiptNumber, ChargeCode, BeginDate, EndDate);

            #region Jake comment and move below code into InitialQuoteEnquiryModel function
            /* Jake comment and move below code into InitialQuoteEnquiryModel function
            QuoteReferenceNumber = string.IsNullOrEmpty(QuoteReferenceNumber) ? string.Empty : HttpUtility.UrlDecode(QuoteReferenceNumber).Trim();
            UserName = string.IsNullOrEmpty(UserName) ? string.Empty : HttpUtility.UrlDecode(UserName).Trim();
            PaymentReceiptNumber = string.IsNullOrEmpty(PaymentReceiptNumber) ? string.Empty : HttpUtility.UrlDecode(PaymentReceiptNumber).Trim();
            ChargeCode = string.IsNullOrEmpty(ChargeCode) ? string.Empty : HttpUtility.UrlDecode(ChargeCode).Trim();

            DateTime beginDate = DateTime.Now.Date.AddDays(-30);
            DateTime endDate = DateTime.Now.Date.AddDays(1).AddSeconds(-1);
            if (BeginDate != "")
            {
                beginDate = Convert.ToDateTime(BeginDate);
            }
            if (EndDate != "")
            {
                endDate = Convert.ToDateTime(EndDate).AddDays(1).AddSeconds(-1);
            }

            int totalCount;
            model.PageSize = Config.PageSize;
            QuoteDB db = new QuoteDB(connectionString);
            DataSet ds = db.GetQuoteList(autIntNo, ChargeCode, UserName, QuoteReferenceNumber, PaymentReceiptNumber, beginDate, endDate, page + 1, model.PageSize, out totalCount);

            if (ds != null)
            {
                if (ds.Tables.Count > 0)
                {
                    DataTable dt = ds.Tables[0];
                    if (dt.Rows.Count > 0)
                    {
                        for (int i = 0; i < dt.Rows.Count; i++)
                        {
                            #region Quote Header

                            QuoteEnquiryModel item = new QuoteEnquiryModel();
                            item.QuHeIntNo = Convert.ToString(dt.Rows[i]["QuHeIntNo"]);
                            item.QuHeReferenceNumber = dt.Rows[i]["QuHeReferenceNumber"] == null ? "" : Convert.ToString(dt.Rows[i]["QuHeReferenceNumber"]);
                            item.QuHeSurName = dt.Rows[i]["QuHeSurName"] == null ? "" : Convert.ToString(dt.Rows[i]["QuHeSurName"]);
                            item.QuHeInitials = dt.Rows[i]["QuHeInitials"] == null ? "" : Convert.ToString(dt.Rows[i]["QuHeInitials"]);
                            item.QuHeIDNumber = dt.Rows[i]["QuHeIDNumber"] == null ? "" : Convert.ToString(dt.Rows[i]["QuHeIDNumber"]);
                            item.QuHeDate = Convert.ToString(dt.Rows[i]["QuHeDate"]) == "" ? "" : Convert.ToDateTime(dt.Rows[i]["QuHeDate"]).ToString("yyyy/MM/dd");
                            item.QuHeAddress1 = Convert.ToString(dt.Rows[i]["QuHeAddress1"]);
                            item.QuHeAddress2 = Convert.ToString(dt.Rows[i]["QuHeAddress2"]);
                            item.QuHeAddress3 = Convert.ToString(dt.Rows[i]["QuHeAddress3"]);
                            item.QuHeAddress4 = Convert.ToString(dt.Rows[i]["QuHeAddress4"]);
                            item.QuHeAddress5 = Convert.ToString(dt.Rows[i]["QuHeAddress5"]);
                            item.ReceiptNo = Convert.ToString(dt.Rows[i]["RctNumber"]);
                            item.ReceiptAmount = double.Parse(dt.Rows[i]["Total"].ToString()).ToString("f2");
                            item.RctIntNo = Convert.ToInt32(dt.Rows[i]["RctIntNo"]);
                            item.Reversed = Convert.ToBoolean(dt.Rows[i]["Reversed"]);
                            model.QuoteEnquiryList.Add(item);

                            #endregion

                            #region Quote Detail

                            if (ds.Tables.Count > 1)
                            {
                                DataRow[] drQuoteDetails = ds.Tables[1].Select("QuHeIntNo=" + item.QuHeIntNo);
                                if (drQuoteDetails != null && drQuoteDetails.Length > 0)
                                {
                                    for (int j = 0; j < drQuoteDetails.Length; j++)
                                    {
                                        QuoteDetailModel itemDetial = new QuoteDetailModel();
                                        itemDetial.QuDeIntNo = Convert.ToString(drQuoteDetails[j]["QuDeIntNo"]);
                                        itemDetial.NTCCode = Convert.ToString(drQuoteDetails[j]["NTCCode"]);
                                        itemDetial.NTCDescr = Convert.ToString(drQuoteDetails[j]["NTCDescr"]);
                                        itemDetial.NTCComment = Convert.ToString(drQuoteDetails[j]["NTCComment"]);
                                        itemDetial.QuDeChargeQuantity = Convert.ToString(drQuoteDetails[j]["QuDeChargeQuantity"]);
                                        itemDetial.MeasureUnit = Convert.ToString(drQuoteDetails[j]["MeasureUnit"]);
                                        itemDetial.NTCStandardAmount = double.Parse(drQuoteDetails[j]["NTCStandardAmount"].ToString()).ToString("f2");
                                        itemDetial.QuDeActualAmount = double.Parse(drQuoteDetails[j]["QuDeActualAmount"].ToString()).ToString("f2");
                                        itemDetial.QuDeGrossAmount = double.Parse(drQuoteDetails[j]["QuDeGrossAmount"].ToString()).ToString("f2");
                                        item.QuoteDetailList.Add(itemDetial);
                                    }
                                }
                            }

                            #endregion

                            #region Receipt Detail

                            if (ds.Tables.Count > 2)
                            {
                                DataRow[] drReceiptDetails = ds.Tables[2].Select("QuHeIntNo=" + item.QuHeIntNo);
                                if (drReceiptDetails != null && drReceiptDetails.Length > 0)
                                {
                                    for (int x = 0; x < drReceiptDetails.Length; x++)
                                    {
                                        ReceiptDetailModel itemDetial = new ReceiptDetailModel();
                                        itemDetial.RTIntNo = Convert.ToString(drReceiptDetails[x]["RTIntNo"]);
                                        itemDetial.RTAmount = double.Parse(drReceiptDetails[x]["RTAmount"].ToString()).ToString("f2");
                                        itemDetial.RTGrossAmount = Convert.ToDouble(drReceiptDetails[x]["RTAmount"]);
                                        itemDetial.RTFineAmount = double.Parse(drReceiptDetails[x]["RTFineAmount"].ToString()).ToString("f2");
                                        itemDetial.RTCashType = GetCashTypeName(Convert.ToString(drReceiptDetails[x]["RTCashType"]));
                                        itemDetial.RctNumber = Convert.ToString(drReceiptDetails[x]["RctNumber"]);
                                        itemDetial.RTDetails = GetRTDetails(Convert.ToString(drReceiptDetails[x]["RTCashType"]), drReceiptDetails[x]);
                                        item.ReceiptDetailList.Add(itemDetial);
                                    }
                                }
                            }

                            #endregion
                        }
                    }
                    else
                    {
                        model.ErrorMsg = QuoteEnquiryListResx.lblErrorText2;
                    }

                }
            }

            model.TotalCount = Convert.ToInt32(totalCount);
            */
            #endregion
            //jake 2015-02-03 added
            model.ShowReversalNTCButton = userInfo.UserRoles.Contains((int)AartoUserRoleList.ReversalOfNTC) && model.TotalCount > 0;

            return View(model);
        }

        [HttpGet]
        public ActionResult CashBox(int page = 0)
        {

SIL.AARTO.Web/Controllers/QuoteManagement/QuoteManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIL.AARTO.BLL.Utility;
using SIL.AARTO.Web.ViewModels.QuoteManagement;

namespace SIL.AARTO.Web.Controllers.QuoteManagement
{
    [AARTOErrorLog]
    public partial class QuoteManagementController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdminReversalForNTC(int page = 0, string QuoteReferenceNumber = "",
            string UserName = "", string PaymentReceiptNumber = "", string ChargeCode = "",
            string BeginDate = "", string EndDate = "")
        {
            UserLoginInfo userInfo = Session["UserLoginInfo"] as UserLoginInfo;
            if (userInfo == null)
            {
                return RedirectToAction("login", "account");
            }
            if (!userInfo.UserRoles.Contains((int)SIL.AARTO.DAL.Entities.AartoUserRoleList.AdminReversalForNTC))
            {
                Response.Write(SIL.AARTO.Web.Resource.QuoteManagement.AdminReversalForNTC.msg_NoPermissionAccess);
                Response.End();
                return View();
            }

            QuoteEnquiryManagementModel model = InitialQuoteEnqiuryModel(page, QuoteReferenceNumber, UserName, PaymentReceiptNumber, ChargeCode, BeginDate, EndDate);

            return View(model);

            //return RedirectToAction("QuoteEnquiryList", new
            //{
            //    page = page,
            //    QuoteReferenceNumber = QuoteReferenceNumber,
            //    UserName = UserName,
            //    PaymentReceiptNumber = PaymentReceiptNumber,
            //    BeginDate = BeginDate,
            //    EndDate = EndDate
            //});
        }
    }
}

SIL.AARTO.Web/Controllers/QuoteManagement/ViewReport_PaidDifferentToQuoteController.cs
using Stalberg.TMS;
using System.Web.Services;
using System.Web.Services.Protocols;
using ceTe.DynamicPDF.ReportWriter.ReportElements;
using ceTe.DynamicPDF;
using ceTe.DynamicPDF.ReportWriter;
using ceTe.DynamicPDF.ReportWriter.Data;
using SIL.AARTO.BLL.Utility;
using System.IO;
using ceTe.DynamicPDF.Imaging;
using System;
using System.Web.Mvc;
using SIL.AARTO.DAL.Entities;
using SIL.AARTO.DAL.Services;
using System.Web;
namespace SIL.AARTO.Web.Controllers.QuoteManagement
{
    public partial class QuoteManagementController : Controller
    {
        SIL.AARTO.BLL.Utility.UserLoginInfo userDetails = new BLL.Utility.UserLoginInfo();
        string login = "";
        int autIntNo = 0;
        protected string styleSheet;
        protected string backgroundImage;
        protected string keywords = String.Empty;
        protected string title = String.Empty;
        string autName = "";

        public ActionResult ViewReport_PaidDifferentToQuote(string BeginDate = "", string EndDate = "",string ReferenceNumber="")
        {
            if (Session["UserLoginInfo"] == null)
            {
                return RedirectToAction("login", "account");
            }

            userDetails = (UserLoginInfo)Session["UserLoginInfo"];
            login = userDetails.UserName;
            autIntNo = Convert.ToInt32(Session["autIntNo"]);

            AuthorityService autService = new AuthorityService();
            SIL.AARTO.DAL.Entities.Authority autEntity = autService.GetByAutIntNo(autIntNo);
            if (autEntity != null)
            {
                autName = autEntity.AutName;
            }

            // Set domain specific variables
            General gen = new General();
            backgroundImage = gen.SetBackground(Session["drBackground"]);
            styleSheet = gen.SetStyleSheet(Session["drStyleSheet"]);
            title = gen.SetTitle(Session["drTitle"]);

            DateTime beginDate = DateTime.Now.Date.AddDays(-30);
            DateTime endDate = DateTime.Now.Date.AddDays(1).AddSeconds(-1);
            if (!string.IsNullOrEmpty(BeginDate))
            {
                beginDate = Convert.ToDateTime(BeginDate);
            }
            if (!string.IsNullOrEmpty(EndDate))
            {
                endDate = Convert.ToDateTime(EndDate).AddDays(1).AddSeconds(-1);
            }

            ReferenceNumber = string.IsNullOrEmpty(ReferenceNumber) ? "" : HttpUtility.UrlDecode(ReferenceNumber).Trim();
            

            var path = HttpContext.Request.PhysicalApplicationPath + @"\Reports\PaidDifferentToQuote.dplx";
            DocumentLayout doc = new DocumentLayout(path);

            try
            {
                ceTe.DynamicPDF.ReportWriter.ReportElements.Label lbl_AutName = (ceTe.DynamicPDF.ReportWriter.ReportElements.Label)doc.GetElementById("lblAutName");
                lbl_AutName.LayingOut += new LayingOutEventHandler(lbl_AutName2);

                StoredProcedureQuery query = (StoredProcedureQuery)doc.GetQueryById("Query");
                query.ConnectionString = connectionString;
                ParameterDictionary parameters = new ParameterDictionary();
                parameters.Add("QuHeReferenceNumber", ReferenceNumber);
                parameters.Add("BeginDate", beginDate);
                parameters.Add("EndDate", endDate);
                parameters.Add("AutIntNo", autIntNo);
                Document report = doc.Run(parameters);
                byte[] buffer = report.Draw();
                return File(report.Draw(), "application/pdf");

            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
                Response.End();
                return View();
            }
        }

        public void lbl_AutName2(object sender, LayingOutEventArgs e)
        {
            try
            {
                ceTe.DynamicPDF.ReportWriter.ReportElements.Label lblRN = (ceTe.DynamicPDF.ReportWriter.ReportElements.Label)sender;

                lblRN.Text = autName;

            }
            catch { }
        }

    }
}

SIL.AARTO.Web/Controllers/Representation/QuoteManagement/Report_PaidDifferentToQuoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIL.AARTO.Web.Controllers.QuoteManagement
{
    public partial class QuoteManagementController : Controller
    {

        public ActionResult Report_PaidDifferentToQuote()
        {
            return View();
        }

    }
}

SIL.AARTO.Web/Views/QuoteManagement/CashBox.cshtml
@model SIL.AARTO.Web.ViewModels.QuoteManagement.CashBoxSelectModel
@using SIL.AARTO.Web.ViewModels.QuoteManagement;
@using SIL.AARTO.Web.Resource.QuoteManagement;
@using SIL.AARTO.Web.Helpers.Paginator
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/Admin.cshtml";
}
<style>
    .listTable
    {
        border-collapse: collapse;
        border-color: gray;
        font-size: 8pt;
        width: 895px;
        border: 1px solid Black;
        text-align: left;
    }

    .headerWhite
    {
        color: White;
        background-color: #6977B0;
    }

</style>

<script type="text/javascript">

    function selectCashBox(cbIntNo,cbName) {
        $("#hidCBIntNo").val(cbIntNo);
        $("#hidCBName").val(cbName);
        
    }

</script>

@using (Html.BeginForm("CashBox", "QuoteManagement"))
{
    <table style="width:300px;" cellspacing="0" cellpadding="4" align="center"  class="listTable">
        <tr class="CartListHead">
            <th class="CartListItem headerWhite" style="text-align:left">@AdminReversalForNTC.lbl_CashboxName</th>
            <th class="CartListItem headerWhite" style="text-align:right">@AdminReversalForNTC.lbl_Float</th>
            <th class="CartListItem headerWhite" style="text-align:center; width:40px;">@AdminReversalForNTC.lbl_Select</th>
        </tr>
        @foreach (CashBoxEntity c in Model.CashBox)
        { 
            <tr class="CartListItem">
                <td class="CartListItem" style="text-align:left">@c.CBName</td>
                <td class="CartListItem" style="text-align:right">@c.CBStartAmount.ToString("0.00")</td>
                <td class="CartListItem" style="text-align:center">@Html.RadioButton("cbxButton", false, new { onclick = "selectCashBox(" + @c.CBIntNo + ",'" + @c.CBName + "');" })
                </td>

            </tr>
        }
        <tr class="CartListHead">
            <td colspan="3" style="text-align: right; padding-right: 4px;">
                @{  var htmlPager = Html.GridPager(new GridPagerProperties { PageKey = "page", PageSize = Model.PageSize, RecordCount = Model.TotalCount, parameters = Model.URLPara }); }
                @Html.Raw(htmlPager)
            </td>
        </tr>
    </table>
    
    <input type="hidden" id="hidCBIntNo" name="hidCBIntNo" />
    <input type="hidden" id="hidCBName"  name="hidCBName"/>
}

SIL.AARTO.Web/Views/QuoteManagement/Report_PaidDifferentToQuote.cshtml
@using SIL.AARTO.Web.Resource.QuoteManagement
@{
    ViewBag.Title = "Report_PaidDifferentToQuote";
    Layout = "~/Views/Shared/Admin.cshtml";
}


<script src="@Url.Content("~/Scripts/ui/jquery.ui.datepicker-ms.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/ui/jquery-ui-timepicker-addon.js")"></script>
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

<style type="text/css">
  

    .lblFontBold
    {
      font-weight:bold;
    }
</style>


<script type="text/javascript">
    $(function () {
        $("#BeginDate").datepicker({ dateFormat: 'yy/mm/dd', changeMonth: true, changeYear: true });
        $("#EndDate").datepicker({ dateFormat: 'yy/mm/dd', changeMonth: true, changeYear: true });
        $("#BeginDate").datepicker('setDate', new Date(new Date() - (86400000 * 30)));
        $("#EndDate").datepicker('setDate', new Date());
    });


function OperSearch() {
  
    var sBeginDate = $("#BeginDate").val();
    var sEndDate = $("#EndDate").val();
    var ReferenceNumber = $.trim($("#txtQuoteReferenceNumber").val());

    if (sBeginDate != "" && sEndDate != "") {
        var beginDate = new Date(sBeginDate.replace("-", "/").replace("-", "/"));
        var endDate = new Date(sEndDate.replace("-", "/").replace("-", "/"));
        if (beginDate > endDate) {
            alert("@Report_PaidDifferentToQuoteResx.lblErrorText1");
            return false;
        }
    }
    var url = "@Url.Action("ViewReport_PaidDifferentToQuote", "QuoteManagement")";
    window.open(url + "?BeginDate=" + sBeginDate + "&EndDate=" + sEndDate + "&ReferenceNumber=" + escape(ReferenceNumber), "_blank");
    //window.open("ViewReport_PaidDifferentToQuote?BeginDate=" + sBeginDate + "&EndDate=" + sEndDate + "&ReferenceNumber=" + escape(ReferenceNumber), "_blank");
 }

</script>

<div style="width: 900px;margin-left:auto;margin-right:auto;">
    <div style="text-align: center;">
        <p>
            <span id="lblPageName" class="ContentHead">@Report_PaidDifferentToQuoteResx.lblPageName</span>
        </p>
        <table align="center">
            <tr>
                <td>
                   <span class="lblFontBold">@Report_PaidDifferentToQuoteResx.lblReferenceNo</span>
                    &nbsp; @Html.TextBox("txtQuoteReferenceNumber", null, new { @class = "Normal", style = "width:150px;" })
                    &nbsp;&nbsp; <span class="lblFontBold">@Report_PaidDifferentToQuoteResx.lblQuoteCreationDate</span>
                    &nbsp;<span class="lblFontBold">From</span> &nbsp;  @Html.TextBox("BeginDate", null, new { @class = "Normal", style = "width:100px;",Readonly="readonly" })
                    &nbsp;<span class="lblFontBold">To</span>&nbsp; @Html.TextBox("EndDate", null, new { @class = "Normal", style = "width:100px;",Readonly="readonly" })
                    &nbsp;&nbsp;<input style="width: 80px; cursor: pointer" type="button" class="NormalButton" id="btnSearch" onclick="OperSearch()" value="@Report_PaidDifferentToQuoteResx.lblSearch" name="btnSearch" />
                </td>
            </tr>
        </table>
      </div>
</div>