SIL.AARTO.Web/Controllers/Enquiry/NoticeNoLookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIL.AARTO.Web.Resource.Enquiry;
using SIL.AARTO.BLL.Utility;
using SIL.AARTO.Web.ViewModels.Enquiry;
using System.Data.SqlClient;
using System.Data;
using Stalberg.TMS;
using SIL.AARTO.BLL.EntLib;
using SIL.AARTO.DAL.Entities;

namespace SIL.AARTO.Web.Controllers.Enquiry
{
    public partial class EnquiryController : Controller
    {
        #region NoticeNoLookup

        public ActionResult NoticeNoLookup(EnquiryModel model)
        {
            if (Session["UserLoginInfo"] == null)
            {
                return RedirectToAction("login", "account");
            }
            string error="";
            string login;
            string sReturn = String.Empty;
            int nAutIntNo;
            string ticketProcessor;// jerry 2011-1-13 add
            int processorSign;// jerry 2011-1-13 add

            string prefix;// Edge 2012-11-09 add
            string sequence;// Edge 2012-11-09 add
            


            // Get user details
            SIL.AARTO.BLL.Utility.UserLoginInfo userDetails = new BLL.Utility.UserLoginInfo();
            userDetails = (UserLoginInfo)Session["UserLoginInfo"];
            login = userDetails.UserName;
            int autIntNo = 0;
            autIntNo = Convert.ToInt32(Session["autIntNo"]);

            // jerry 2011-1-13 add
            ticketProcessor = Session["TicketProcessor"] != null ? Session["TicketProcessor"].ToString() : "TMS";
            if (ticketProcessor.Equals("TMS") || ticketProcessor.Equals("Cip_CofCT") || ticketProcessor.Equals("CiprusPI"))
            {
                processorSign = 1;
            }
            else
            {
                processorSign = 2;
            }

            sReturn = string.Empty;
            model.originalTicketNo = "";
            if (model.NoticeNoLookupSubmitToAction != null && model.NoticeNoLookupSubmitToAction == "EnquiryList")
            {
                Session["ISFromNoticeLookup"] = 1;
            }
       
            DataTable dt = null;
            if (model.searchField2 == null || model.searchField2 == "")
            {
                model.searchField2 = "TickSequenceNo";
            }
            if (model.searchField2 == "TickSequenceNo")
            {
                dt = Search_Ticket(model, processorSign, ticketProcessor, out error);
            }
            else
            {
                // model.searchField = "EasyPayNo";

                dt = Search_EasyPay(model, out error);
            }
            model.LookUpErrorMsg = error;
            if (error != "")
            {
                model.NoticeNoLookupHasError = "1";

                TempData["EnquiryModel"] = model;
                return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
            }
            if (dt == null || dt.Rows.Count == 0)
            {
                if (model.searchField2 == "TickSequenceNo")
                {
                    if (model.CDV == null)
                    {
                        model.CDV = "";
                    }
                    if (model.Prefix == null)
                    {
                        model.Prefix = "";
                    }
                    if (model.Sequence == null)
                    {
                        model.Sequence = "";
                    }
                    if (model.AuthCode==null)
                    {
                        model.AuthCode = "";
                    }
                    string sNoticeNumber = model.Prefix.Trim() + "/" + model.Sequence.Trim() + "/" + model.AuthCode.Trim() + "/" + model.CDV.Trim();
                    model.LookUpErrorMsg = string.Format("{0} {1} {2}", NoticeNoLookupRes.lblErrorText9, sNoticeNumber, NoticeNoLookupRes.lblErrorText10);
                    model.TicketNo = model.Prefix.Trim() + model.Sequence.Trim() + model.AuthCode.Trim() + model.CDV.Trim();
                    model.searchField = "TicketNo";
                    TempData["EnquiryModel"] = model;
                    return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
                }
                else
                {
                    model.TicketNo = "";
                    model.searchField = "TicketNo";
                    TempData["EnquiryModel"] = model;
                    return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
                }
            }

            if (dt != null && dt.Rows.Count == 1)
            {
                sReturn = dt.Rows[0]["NotTicketNo_Enquiry"] == null ? "" : Convert.ToString(dt.Rows[0]["NotTicketNo_Enquiry"]);

                string ticketNo = dt.Rows[0]["NotTicketNo"] == null ? "" : Convert.ToString(dt.Rows[0]["NotTicketNo"]);
                if (ticketNo.IndexOf("/") > 0)
                {
                    model.Prefix = ticketNo.Split('/')[0];
                    model.Sequence = ticketNo.Split('/')[1];
                }
                model.TicketNo = sReturn;
                model.searchField = "TicketNo";
                TempData["EnquiryModel"] = model;
                return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
               
            }
            else if (dt != null && dt.Rows.Count > 1)
            {
                
                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        Header item = new Header();
                        item.NotTicketNo_Enquiry = dt.Rows[i]["NotTicketNo_Enquiry"] == null ? "" : Convert.ToString(dt.Rows[i]["NotTicketNo_Enquiry"]);
                        item.NotTicketNo = dt.Rows[i]["NotTicketNo"] == null ? "" : Convert.ToString(dt.Rows[i]["NotTicketNo"]);
                        item.NotRegNo = dt.Rows[i]["NotRegNo"] == null ? "" : Convert.ToString(dt.Rows[i]["NotRegNo"]);
                        item.Name = dt.Rows[i]["Name"] == null ? "" : Convert.ToString(dt.Rows[i]["Name"]);
                        item.NotIntNo = dt.Rows[i]["NotIntNo"] == null ? 0 : Convert.ToInt32(dt.Rows[i]["NotIntNo"]);
                        model.HeaderList.Add(item);
                       
                    }
                    model.TicketNo = "";
                    model.searchField = "RegNo";
            }
            else
            {
               sReturn = model.Prefix.Trim() + model.Sequence.Trim() + model.AuthCode.Trim() + model.CDV.Trim();
               model.Sequence = string.Empty;
               model.TicketNo = sReturn;
               model.searchField = "TicketNo";
               TempData["EnquiryModel"] = model;
               return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
            }

            TempData["EnquiryModel"] = model;
            return RedirectToAction(model.NoticeNoLookupSubmitToAction, model.NoticeNoLookupSubmitToController);
          
        }

       
      

        public DataTable Search_Ticket(EnquiryModel model, int processorSign, string ticketProcessor, out string error)
        {

            // Heidi 2014-10-16 added "try catch and WriteLog" for fixing AARTOErrorLog shows issue.(5367)
            error = "";
            try
            {
                char cTemp = Convert.ToChar("0");
                int autIntNo = Convert.ToInt32(Session["autIntNo"]);
                SIL.AARTO.BLL.Utility.UserLoginInfo userDetails = new BLL.Utility.UserLoginInfo();
                userDetails = (UserLoginInfo)Session["UserLoginInfo"];
                string login = userDetails.UserName;

                int nCdv;
                int nSeq;
                String sNoticeNumber = string.Empty;

                NoticeDB ndb = new NoticeDB(connectionString);
                //SqlDataReader reader = null;

                DataTable dt = new DataTable();

                if (model.Prefix != null && model.Prefix.Trim().Length == 0)
                {
                    //2012-3-6 linda modified into a multi-language
                    error = NoticeNoLookupRes.lblErrorText;
                    return null;
                }

                if (processorSign == 1)//processor is TMS
                {
                    // TMS Ticket Processors
                    // Order of text boxes:
                    //  1.	1st text box = Notice Prefix/Document Type  blank, user must enter (might be hidden if AuthRule 4905 Rule to hide prefix in Ticket Search = ‘Y’)
                    //  2.	2nd text box = Sequence no  blank, user must enter
                    //  3.	3rd text box = Authority.AutNo for current Authority (pre-populate)

                    //Heidi 2014-10-16 added validation for fixing AARTOErrorLog shows issue.(5367)
                    if ((model.Prefix == null) || (model.Prefix != null && model.Prefix.Trim().Length == 0))
                    {
                        error = NoticeNoLookupRes.lblErrorText1 + ticketProcessor + NoticeNoLookupRes.lblErrorText6;
                        model.setControlFocus = "txtPrefix";
                        return null;
                    }

                    if ((model.Sequence == null) || (model.Sequence != null && model.Sequence.Trim().Length == 0))
                    {
                        //2012-3-6 linda modified into a multi-language
                        error = NoticeNoLookupRes.lblErrorText1 + ticketProcessor + NoticeNoLookupRes.lblErrorText8;
                        //txtNumber.Focus();
                        model.setControlFocus = "txtNumber";
                        return null;
                    }

                    if ((model.AuthCode == null) || (model.AuthCode != null && model.AuthCode.Trim().Length == 0))
                    {
                        //2012-3-6 linda modified into a multi-language

SIL.AARTO.Web/Views/Shared/Admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href='@Url.Content("~/Content/Css/Admin/Admin.css")' rel="stylesheet" type="text/css" />
    <link href='@Url.Content("~/Content/Css/Global.css")' rel="stylesheet" type="text/css" />
    <link href='@Url.Content("~/Content/Css/ST_Odyssey.css")' rel="stylesheet"  type="text/css" />
    <link href='@Url.Content("~/Content/themes/base/jquery-ui.css")' rel="stylesheet"  type="text/css" />
    <script src='@Url.Content("~/Scripts/jquery-1.4.4.min.js")' type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    <script type="text/javascript" src='@Url.Content("~/RootPathHandler.ashx")'></script>
    @RenderSection("HeaderContent", false)
</head>

<body>
    <div>
        @{if (Session["UserLoginInfo"] == null)
            {

            <script type="text/javascript">
                window.parent.parent.location = _ROOTPATH + "/Account/Login";
            </script>

            }
        }
        @RenderBody()
    </div>
</body>
</html>

SIL.AARTO.Web/Views/Shared/MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @RenderSection("header", false)
</head>
<body>
    <div>
        @if (Session["UserLoginInfo"] == null)
        {
        <script type="text/javascript">
            window.parent.parent.location = _ROOTPATH + "/Account/Login";
        </script>
        }
        @RenderBody()
    </div>
</body>
</html>

SIL.AARTO.Web/Views/Shared/MulityLangPartView.cshtml
@using SIL.AARTO.DAL.Entities;
@model SIL.AARTO.Web.ViewModels.LookupPartViewModel
<div>
    <table cellspacing="0" border="0" style="background-color:Silver;width:350px;border-collapse:collapse;" id="LanguageLookupTb">
        <tbody>
        @foreach (var item in Model.LanguageSelectors)
        {
            if (item.LsCode == "en-US")
            {
            <tr>
                <td>@item.LsDescription</td>
                <td>
                    <input id="mul_en-US" 
                        class="Normal input-validation-error" 
                        type="text" 
                        value="" style="width:260px;height:21px;" name="mul_en-US" 
                        data-val-required="*" 
                        data-val-length-max="@Model.EnUSLength" 
                        data-val-length="Max length @Model.EnUSLength" 
                        data-val="true">
                        @Html.ValidationMessage("mul_en-US", new { title="Required Field" })
                </td>
            </tr>
            }
            else
            {
            <tr>
                <td>@item.LsDescription</td>
                <td>
                    @Html.TextBox("mul_" + item.LsCode, null, new { style = "height:21px;width:260px;" })
                </td>
            </tr>
            }
        }
        </tbody>
    </table>
</div>

SIL.AARTO.Web/Views/Shared/NonCameraImagePartialView.cshtml
@using SIL.AARTO.Web.Resource.Enquiry
@model SIL.AARTO.Web.ViewModels.Enquiry.NonCameraImageModel
<script src="@Url.Content("~/Scripts/Jquery/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Jquery/ui.core.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Jquery/ui.draggable.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Jquery/jquery.rightClick.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Jquery/jquery-1.8.3.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Jquery/jquery-ui.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/Css/ST_Odyssey.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    //2014-02-18 Heidi added for download images(5188)
    $(function () {
        $("#btnDownLoadImage").click(function () {
            var url = $("#mainImage").attr("src");
            var arr = url.split("?");
            document.location.href = "@Url.Action("DownLoadImage", "Enquiry")" + "?" + arr[1];
        });
    })
 </script>
<div id="div_message" style="display: none; height: 30px; line-height: 30px; padding-top: 10px;">@NonCameraRes.Nodata</div>
<div id="div_show">
    <table width="100%">
        <tr>
            <td colspan="3">
            </td>
            <div id="mainImageDiv" style="width: 630px; height: 800px; line-height: 800px; overflow: auto;
                position: relative; margin-left: auto; margin-right: auto;">
                <div id="rect" class="Rect" style="display: none">
                </div>
                <img alt="" id="mainImage" src="" style="position: absolute" />
            </div>
        </tr>
        <tr>
            <td width="200">
                <input id="btnPrev" onclick="prev()" class="NormalButton" value="@NonCameraRes.btnPrev" type="button" />
                <input id="btnNext" class="NormalButton" onclick="next()" value="@NonCameraRes.btnNext" type="button" />
                <span id="span_num"></span>
            </td>
            <td width="500">
                <input id="btnZoom" class="NormalButton" type="button" clientidmode="Static" runat="server"
                    value="@NonCameraRes.btnZoom" style="width: 150px" />
                <input id="btnDownLoadImage" value="@NonCameraRes.btnDownloadImage" type="button" class="NormalButton" />
            </td>
            <td width="450" align="left">
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <span id="lblFeedback" runat="server" clientidmode="Static" style="color: Red; border: solid 1px #ccc">
                </span>
            </td>
        </tr>
    </table>
</div>
<input id="hd_notIntNO" type="hidden" runat="server" value="0" />
@Html.HiddenFor(model => model.ImageUrls)
<script type="text/javascript">
    var mainImageID = "mainImage";
    //  var MainSrc = "/Images/Image.aspx.jpg";
    //var imgArr = ["Images/111.JPG", "Images/Bluehills.jpg", "Images/111.JPG"];
    var lblFeedbackID = "lblFeedback";
    var imgstr = $("#ImageUrls").val(); // '<%=imageUrls %>'

    var imgArr = imgstr.split(',');

    var i = 0;
    var arrlenth = 0;
    arrlenth = imgArr.length;
    function prev() {

        $("#btnNext").removeAttr("disabled");

        if (arrlenth > 0) {
            if (i > 0) {
                i = i - 1;
                $("#mainImage").attr("src", imgArr[i]);
            }
            if (i == 0) {
                $("#btnPrev").attr("disabled", "disabled");
            }
        }
        $("#span_num").html((i + 1) + "/" + arrlenth);

    }

    function next() {


        $("#btnPrev").removeAttr("disabled");
        if (arrlenth > 0) {
            if (i < arrlenth - 1) {
                i = i + 1;
                $("#mainImage").attr("src", imgArr[i]);
            }
            if (i == arrlenth - 1)
            { $("#btnNext").attr("disabled", "disabled"); }
        }
        $("#span_num").html((i + 1) + "/" + arrlenth);

    }

    $(function () {
        if (arrlenth > 0) {
            $("#mainImage").attr("src", imgArr[0]);
            $("#span_num").html((i + 1) + "/" + arrlenth);

        }
        if (imgstr.length == 0) {
            $("#div_show").hide();
            $("#div_message").show();
        }
        if (arrlenth == 1) {
            $("#btnNext").attr("disabled", "disabled");
            $("#btnPrev").attr("disabled", "disabled");

        }
        pageLoad();
        $("#mainImage").draggable();
    })
    
  
</script>
<script type="text/javascript" src="@Url.Content("~/Scripts/nonCameraZoom.js")"></script>

SIL.AARTO.Web/Views/Shared/NoticeNoLookup.cshtml
@using SIL.AARTO.Web.Resource.Enquiry;
@model SIL.AARTO.Web.ViewModels.Enquiry.EnquiryModel
<script type="text/javascript">
    function AutoQueue() {
        var NPrefix = $("#Prefix").val();
        if (NPrefix.toString().length >= 2) {
            $("#Sequence").focus();
        }
    }

    function LookUpSubmitAction(obj) {
        $("#NoticeNoLookupHasError").val("");
        $("#mainform").attr("action",_ROOTPATH+"/Enquiry/NoticeNoLookup");
        $("#mainform").submit();
        }

    $(function () {

        $("#EasyPayNo").focus(function () {
            $("#searchField2").val("EasyPayNo"); 
        });
        $("#Prefix").focus(function () {
            $("#searchField2").val("TickSequenceNo"); 
        });
        $("#Sequence").focus(function () {
            $("#searchField2").val("TickSequenceNo"); 
        });
        $("#AuthCode").focus(function () {
            $("#searchField2").val("TickSequenceNo"); 
        });
    })

</script>
<table width="100%">
    <tr align="center">
        <td align="center" valign="middle" class="NormalBold" colspan="2" >
            <div  style="width:600px; height:30px;">
            @Html.Label("", NoticeNoLookupRes.lbLookUpText, new { id = "lbLookUp", @class = "NormalBold"})
             <input id="btnLookUp" name="btnLookUp" class="NormalButton"  onclick="LookUpSubmitAction(this)"  type="button" style='width:80px;float:right;margin-right:50px' value=" @NoticeNoLookupRes.btnSearchText"/>
                </div>
        </td>
        
       
    </tr>
    <tr align="center">
        <td colspan="2">
         <table class="Normal">
                <tr style="height: 22">
                    <td width="250px" align="left">
                        @Html.Label("", NoticeNoLookupRes.lbTickSequenceNoText, new { id = "lbTickSequenceNo", @class = "NormalBold" })
                    </td>
                    <td align="left" width="541px">
                        @Html.TextBoxFor(model => model.Prefix, new { @class = "Panel1 DisableTextBox2", style = "width:50px", onkeyup = "AutoQueue()" })
                        @Html.TextBoxFor(model => model.Sequence, new { @class = "Panel1 DisableTextBox2", style = "width:60px", maxLength = "6" })
                        @Html.TextBoxFor(model => model.AuthCode, new { @class = "Panel1 DisableTextBox2", style = "width:84px", maxLength = "9" })
                        @Html.TextBoxFor(model => model.CDV, new { style = "width:45px", disabled = "disabled" })
                         @Html.HiddenFor(model => model.searchField2) 
                          @Html.HiddenFor(model => model.NoticeNoLookupHasError) 
                    </td>
                </tr>
                <tr align="center" style="height: 22">
                    <td align="left">
                        @Html.Label("", NoticeNoLookupRes.lbEasyPayNoText, new { @class = "NormalBold", id = "lbEasyPayNo" })
                    </td>
                    <td align="left">
                        @Html.TextBoxFor(model => model.EasyPayNo, new { @class = "Panel1 DisableTextBox2", style = "width:215px" })
                    </td>
                </tr>
            </table>
           <table width="100%">
                <tr>
                    <td>
                        @{
                            if (Model.HeaderList != null && Model.HeaderList.Count > 0)
                            {
                            <table class="listTable">
                                <thead>
                                    <tr class="CartListHead">
                                        <th scope="col" width="150px;">@NoticeNoLookupRes.grdHeaderHeaderText1
                                        </th>
                                        <th scope="col" width="100px;">@NoticeNoLookupRes.grdHeaderHeaderText2
                                        </th>
                                        <th scope="col" width="100px;">@NoticeNoLookupRes.grdHeaderHeaderText3
                                        </th>
                                        <th scope="col" width="50px;">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0; i < Model.HeaderList.Count; i++)
                                    {
                                        var hederEntity = Model.HeaderList[i];
                                        <tr class="CartListItem">
                                            <td class="CartListItem">
                                                @hederEntity.NotTicketNo_Enquiry
                                            </td>
                                            <td class="CartListItem">
                                                @hederEntity.NotRegNo
                                            </td>
                                            <td class="CartListItem">
                                                @hederEntity.Name
                                            </td>
                                            <td class="CartListItem">
                                                <input id="btnSelect" style="cursor: pointer"  name="btnSelect" onclick="SelectSubmit2(this)"  class="NormalButton" type="button" value="Select"/>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                                   
                            }
                        }
                         <span id="lblLookUpError" style="color: Red; font-weight: bold">@Model.LookUpErrorMsg</span>

                        &nbsp;
                    </td>
                </tr>
            </table>
                @Html.HiddenFor(model => model.NoticeNoLookupSubmitToAction)
                @Html.HiddenFor(model=>model.NoticeNoLookupSubmitToController)
                
        </td>
    </tr>
</table>

SIL.AARTO.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href='@Url.Content("~/Content/Css/Admin/Admin.css")' rel="stylesheet" type="text/css" />
    <link href='@Url.Content("~/Content/Css/Global.css")' rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Css/ST_Odyssey.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
     <script type="text/javascript" src='@Url.Content("~/RootPathHandler.ashx")'></script>

    <script type="text/javascript">
        // IE 8 Fix for arrays that miss the indexOf Method. This fix requires JQuery.
        if (!Array.prototype.indexOf) {
            Array.prototype.indexOf = function (val) {
                return jQuery.inArray(val, this);
            };
        }
    </script>

    @RenderSection("header",false)
</head>

<body>
    @RenderBody()
</body>
</html>